name: Get Jeff Johnson NOW
favicon: null
layout_spectrum: 0.50458
typography_spectrum: 0.852975346846506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e5e5'
    - '#6ec0ec'
    - '#111111'
    - '#73482d'
    - '#a4704e'
  brandStrength: 0.9952554288320243
  lightness: 0.6735914070159197
  saturation: 0.9930513151921332
  rhythmicContrast: 0.7324226929340512
purpose: []
